[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "1.3.0"
update_changelog_on_bump = true
version_files = [
    "pyproject.toml:version",
    "__version__.py"
]